name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # WHOOOPS dropped the colon here.
  build
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: echo "running"
